openapi: 3.0.1
info:
  title: SmsSender
  contact: {}
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: '2.0'
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /{municipalityId}/send/sms:
    post:
      tags:
      - SMS Resources
      summary: Send an SMS
      operationId: sendSms
      parameters:
      - name: municipalityId
        in: path
        description: Municipality id
        required: true
        schema:
          type: string
        example: 2281
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendSmsRequest"
        required: true
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Problem"
        "200":
          description: Successful Operation
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/SendSmsResponse"
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Problem"
  /api-docs:
    get:
      tags:
      - API
      summary: OpenAPI
      operationId: getApiDocs
      responses:
        "200":
          description: OK
          content:
            application/yaml:
              schema:
                type: string
      x-auth-type: None
      x-throttling-tier: Unlimited
      x-wso2-mutual-ssl: Optional
components:
  schemas:
    SendSmsRequest:
      required:
      - message
      - mobileNumber
      - sender
      type: object
      properties:
        sender:
          $ref: "#/components/schemas/Sender"
        mobileNumber:
          type: string
          description: Mobile number incl. country code
          example: "+46701234567"
        priority:
          type: string
          description: Priority - indicates whether the SMS may be sent between 20:00
            and 08:00 or not
          default: NORMAL
          enum:
          - HIGH
          - NORMAL
        message:
          type: string
    Sender:
      required:
      - name
      type: object
      properties:
        name:
          maxLength: 11
          minLength: 3
          type: string
          description: "The sender of the SMS, swedish letters(å,ä,ö) will be replaced\
            \ by (a,a,o) respectively"
          example: sender
    Problem:
      type: object
      properties:
        parameters:
          type: object
          additionalProperties:
            type: object
        instance:
          type: string
          format: uri
        type:
          type: string
          format: uri
        title:
          type: string
        detail:
          type: string
        status:
          $ref: "#/components/schemas/StatusType"
    StatusType:
      type: object
      properties:
        reasonPhrase:
          type: string
        statusCode:
          type: integer
          format: int32
    SendSmsResponse:
      type: object
      properties:
        sent:
          type: boolean
  securitySchemes: {}
